name: Tests

on:
  pull_request:
    branches:
      - main
      - 'dev-**/main'
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v7
      - run: uv sync --group dev
      - run: uv run pytest tests
